### ISSUE TITLE
[Bug] Forge 1.19.2 crash

### ISSUE THREAD

**Issue by thimblebird** [melontini/recipe_book_is_pain#10]
see https://github.com/melontini/recipe_book_is_pain/issues/9#issuecomment-1296361605

**Comment by melontini** [comment]
So, after rewriting the mod for the 3rd time, I believe this should be fixed. 
Can you confirm if [this version](https://github.com/melontini/recipe_book_is_pain/suites/9104234974/artifacts/422250626) works for you?

**Comment by thimblebird** [comment]
Confirmed! 💚🐢
