### ISSUE TITLE
[Visual Bug] Mouse Wheelie Page Switching

### ISSUE THREAD

**Issue by JLUsr** [melontini/recipe_book_is_pain#11]
I know that v0.8.0 is an Experimental release but I thought it might be useful to mention that this version has a visual bug with page switching through Mouse Wheelie.

[Version 0.7.1]
![javaw_Tuesday_2023-02-07_14-43-23](https://user-images.githubusercontent.com/47650360/217383933-44c278b4-876a-47c3-a7f6-04f108fb551a.gif)

[Version 0.8.0]
![javaw_Tuesday_2023-02-07_14-48-40](https://user-images.githubusercontent.com/47650360/217384735-144f9656-d6b9-4b65-873c-b7283ec45963.gif)

**Comment by melontini** [comment]
Hi, thanks for the report, can you please tell me what version of Minecraft you are using?

**Comment by melontini** [comment]
I think I've fixed it. Can you please check if this build works for you? 
https://github.com/melontini/recipe_book_is_pain/actions/runs/4123601723
