### ISSUE TITLE
[Bug] Crash with Bag Of Holding

### ISSUE THREAD

**Issue by SplendidAlakey** [melontini/recipe_book_is_pain#13]
**Describe the bug**

Recipe Book is Pain 0.9.0 is incompatible with [Bag Of Holding](https://www.curseforge.com/minecraft/mc-mods/bag-of-holding-forge/files/4111699).

**To Reproduce**

Simply install both mods and run the game.

**Expected behavior**

No crash.

**Logs**

https://gist.github.com/SplendidAlakey/d6796cc206e150ee98f11b8591f285a1

**Environment:**

 - Minecraft Version 1.19.2
 - Mod Version 0.9.0 Fabric

**Additional context**

I know the report blames Bag Of Holding, but I'm reporting here, because it's the Recipe Book is Pain update, that introduced the crash. Though, removing the Bag Of Holding does let the game start, too.

Reverting Recipe Book is Pain to 0.8.1 also helps.

**Comment by melontini** [comment]
Oh, I know exactly why this happens. 

Bag Of Holding uses [extensibleenums](https://github.com/Fuzss/extensibleenums) to extend enums. 
extensibleenums assumes that `$VALUES` of an enum are always `Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL | Opcodes.ACC_SYNTHETIC`, while  `Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC | Opcodes.ACC_SYNTHETIC` are almost always true, the `Opcodes.ACC_FINAL` gets removed in certain cases like this: 

```
    @Shadow
    @Final
    @Mutable
    private static EnchantmentTarget[] field_9077;
```

which is exactly what's happening here [EnchantmentTargetMixin](https://github.com/melontini/cracker-util/blob/1.19.2-fabric/src/main/java/me/melontini/crackerutil/mixin/enhanced_enums/EnchantmentTargetMixin.java) or almost the same thing here [RuntimeEnumExtender](https://github.com/AlphaMode/FabricExtendibleEnum/blob/a6a23b744354b72e80ca4a0dae5727b4071fe3a4/src/main/java/net/alphamode/enums/RuntimeEnumExtender.java#L144) (which also fails btw)

I'm not sure if there's a fix from my side. But I'll try to hack something up.

**Comment by melontini** [comment]
Okay, I came up with a hack. I'll try to release it ~soonish.

```java
@Mixin(UnsafeExtensibleEnum.class)
@MixinShouldApply(mods = @Mod("extensibleenums"))
public class UnsafeExtensibleEnumMixin {
    @ModifyConstant(method = "addToEnumValues", constant = @Constant(intValue = 4122), remap = false, require = 0)
    private static int cracker_util$skipFinalCheck(int value) {
        return 4106;
    }
}
```

I should really start publishing CrackerUtil on Curse and Modrinth...

**Comment by melontini** [comment]
Hello again, this should be fixed in the latest version of CrackerUtil. I've uploaded it on [modrinth ](https://modrinth.com/mod/cracker-util) (Whenever it gets approved) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cracker-util).
