### ISSUE TITLE
[Bug] modrinth latest version is saying 9.3.0 is more recent then 9.4.0

### ISSUE THREAD

**Issue by Taleuxss** [melontini/recipe_book_is_pain#16]
use prism to update mods and it says old version 9.4.0 new version 9.3.0

**Comment by melontini** [comment]
Weird, the version numbers are correct. It might be assuming the featured 0.9.3 is the latest. 

I've unfeatured 0.9.3. Can you check if it's correct now?

**Comment by Taleuxss** [comment]
you fixed it
