### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Azzarg** [melontini/recipe_book_is_pain#19]
**Describe the bug**
Minecraft crashes while loading world as long as this mod is installed.

**To Reproduce**
1. Install the mod, even by itself
2. Create a world or load an existing one
3. Crash

**Expected behavior**
I expect the game to continue working

**Environment:**
 - Minecraft version 1.20.1
 - Mod Version 0.9.0

**Logs**
[recipe book crash.txt](https://github.com/melontini/recipe_book_is_pain/files/13775062/recipe.book.crash.txt)

**Comment by zenfyrdev** [comment]
Official Forge support has been dropped forever ago. If you want to use the mod on Forge, you should try https://modrinth.com/mod/connector
