### ISSUE TITLE
Scroll Based on Mouse Location

### ISSUE THREAD

**Issue by ardissaps** [melontini/recipe_book_is_pain#2]
Currently if we already scroll the recipe we cant scroll the tab, need to click the tab if want to scroll the tab. Thanks!

**Comment by melontini** [comment]
I believe this will conflict with better recipe books, since it's the mod which adds scrolling in the first place.

**Comment by ardissaps** [comment]
I see, it is not big deal actually, as the scroll is actually work if the current opened tab is on same page we are opening. Just need to get used to it. Thanks!

**Comment by ardissaps** [comment]
Look like the scroll is working great now, I have posted another idea on another post : https://github.com/melontini/recipe_book_is_pain/issues/4
