### ISSUE TITLE
Lost Connection: Timed Out

### ISSUE THREAD

**Issue by scamish76** [melontini/recipe_book_is_pain#21]
### What happened?

I tried getting your latest release to work 0.11.1 (1.20.4).... it doesn't. Thinking it was a mod conflict issue, I disabled all my other mods, still no go. I get a time out error. 

 Your previous version 0.11.0 worked. 
 
 

### Logs

https://mclo.gs/oyzbEGo

### Version

0.11.1 (1.20.4)

**Comment by zenfyrdev** [comment]
Hi, please try with Fabric Loader 0.15.10

**Comment by scamish76** [comment]
hey, that fixed the problem. thank you
