### ISSUE TITLE
Automatically Switch Page According to Opened Tab Group

### ISSUE THREAD

**Issue by ardissaps** [melontini/recipe_book_is_pain#4]
Scroll is working now, just 1 more addition that would make it perfect, would you make these  :
![image](https://user-images.githubusercontent.com/82106625/178751238-a92900bb-4903-4920-8068-449250593193.png)
The picture is currently opening Farmer Delight that is on the page 7 (via scrolling the group), would be great if the page is automatically switch to page 7 without manually change page.

**Comment by ardissaps** [comment]
> Sooo, I tried adding this feature, but...
> I couldn't figure out which mod adds scrolling around tabs, since it's not RBIP and not BRB and also not crafting tweaks.
> 
> Could you please check if any other mod adds that?

Mouse Wheelie?

**Comment by melontini** [comment]
Well, I have some bad news. 
This, sadly, doesn't seem possible.

**Comment by ardissaps** [comment]
It is ok. Thank you for the mods!

**Comment by melontini** [comment]
I'm going to leave this issue open for now.
Maybe I, or someone else, will figure out a good way of adding this.

**Comment by melontini** [comment]
Well, I've got some good news!

**Comment by melontini** [comment]
A new version fixing this is out on modrinth!
https://modrinth.com/mod/rbip/version/0.6

P.S. I'll upload it to curseforge when it's not down.

**Comment by ardissaps** [comment]
Nice, thanks!
