### ISSUE TITLE
[Question] "this mod does not require Fabric API" 

### ISSUE THREAD

**Issue by Taknax** [melontini/recipe_book_is_pain#5]
Hi. This is very useful. Do you plan a Forge version for 1.18.2 and 1.19.1 (When forge once get updated)?

**Comment by melontini** [comment]
Hey, thanks for asking.

I actually tried to port this mod to forge, but I couldn't get past the loading screen with the least descriptive error message ever.
So, there might be a forge version, if I find a way to fix this.

**Comment by melontini** [comment]
Forge version is now out: (1.18.2 only. For now)

https://modrinth.com/mod/rbip/version/0.6-1.18-forge

https://www.curseforge.com/minecraft/mc-mods/recipe-book-is-pain/files/3884622
