### ISSUE TITLE
1.18.2 0.7 forge crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [melontini/recipe_book_is_pain#9]
The new version does not start. 

Latest: https://0x0.st/oYjl.txt
Crash: https://0x0.st/oYjU.txt

**Comment by melontini** [comment]
That's interesting... It works fine on its own.
I can't tell you what's going on right now. I'll look closer later.

Sorry for the inconvenience 😅

**Comment by agentwolf88** [comment]
No problem, take your time and keep up your good work!

**Comment by thimblebird** [comment]
same for forge 1.19.2 and 0.7, but version 0.6 already didn't work (crash at startup):

crash: https://pastebin.com/xt4nh9BV
[debug.log](https://github.com/melontini/recipe_book_is_pain/files/9896932/debug.log)

**Comment by melontini** [comment]
> No problem, take your time and keep up your good work!

@agentwolf88 sooo, I think I fixed the 1.18 version.

Could you please check out if [this version](https://github.com/melontini/recipe_book_is_pain/suites/9039093326/artifacts/417488801) works for you?

**Comment by agentwolf88** [comment]
Works fine now. :D THX!

**Comment by melontini** [comment]
> Should I create a separate issue for 1.19.2?

Yeah.
Also, I still don't know what the problem with 1.19 is. Seems like forge changed more things internally. I'm not sure how soon (or if at all) I can fix this.
